Repository codewithdev/C-plus-plus-Algorithms, pull requests merged in 2021-10, with the labels that each got.

#105 Added Grumpy Bookstore Problem
  ONLINE JUDGE/LeetCode/#1052- Grumpy-Bookstore.cpp
Labels: hactoberfest-accepted

#102 Added Dynamic Programming and Recursion Problems
  10- Recursion & Backtracking/LCS.cpp
  10- Recursion & Backtracking/countofSubsetsWithGivenDifference.cpp
  10- Recursion & Backtracking/countofSubsetsWithgivenSum.cpp
  10- Recursion & Backtracking/deleteMiddleElementofStackRecursion.cpp
  10- Recursion & Backtracking/editDistanceRecursive.cpp
  10- Recursion & Backtracking/isEqualSumPartitionPossible.cpp
  10- Recursion & Backtracking/isSubsetSumPossible.cpp
  10- Recursion & Backtracking/sortArrayRecursion.cpp
  10- Recursion & Backtracking/sortStackDescendingRecursion.cpp
  24- Dynamic Programming/MCMMemoized.cpp
Labels: hactoberfest-accepted

#106 Added Rabin Miller Algorithm
  09- Number Theory/rabinMiller.cpp
Labels: hactoberfest-accepted

#108 Create Partition-list.cpp
  ONLINE JUDGE/LeetCode/#86-Partition-list.cpp
Labels: hactoberfest-accepted

#111 create-sum-of-all-nodes.cpp
  18-Binary Tree/sum-of-all-nodes.cpp
Labels: hactoberfest-accepted, triage

#110 Added Graph Theory Algorithms
  25-Graph Theory/bipartiteGraphTest.cpp
  25-Graph Theory/connectedComponents.cpp
  25-Graph Theory/dijkstras.cpp
Labels: hactoberfest-accepted, triage

#112 Created a solution to a famous dynamic programming problem "0-1 knapsack"the online judge used for testing is atcoder
  24- Dynamic Programming/Knapsack.cpp
Labels: hactoberfest-accepted, add code

#109 Create 3sum_closest.cpp
  03-Arrays/3sum_closest.cpp
Labels: hactoberfest-accepted

#113 Added Mobius Function in Number Theory
  09- Number Theory/Mobius.cpp
Labels: hactoberfest-accepted

#122 Create #34- swap-nodes.cpp
  ONLINE JUDGE/LeetCode/#34- swap-nodes.cpp
Labels: hactoberfest-accepted

#124 Jump Search
  05-Searching/JumpSearch.cpp
Labels: hactoberfest-accepted
